FormWeb/Pages/Customer/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using FormWeb.Models;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace FormWeb.Pages.Customer
{
    public class CreateModel : PageModel
    {
        private readonly FormWeb.Models.ESHOPDBContext _context;

        public CreateModel(FormWeb.Models.ESHOPDBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Tblcustomer Tblcustomer { get; set; }
        [BindProperty]
        public List<Tbljob> Tbljobs { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            Tbljobs = await _context.Tbljobs.ToListAsync();
            //Tblcustomer.CreateDate = DateTime.Now;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                int code = GetCodeCustomer();

                if (Tblcustomer.Code == null || Tblcustomer.Code == "")
                {
                    if (code >= 100)
                    {
                        Tblcustomer.Code = "CD" + code.ToString();
                    }
                    else if (code >= 10)
                    {
                        Tblcustomer.Code = "CD0" + code.ToString();
                    }
                    else
                    {
                        Tblcustomer.Code = "CD00" + code.ToString();
                    }
                }

                if (Tblcustomer.Status == null || Tblcustomer.Status == "")
                {
                    Tblcustomer.Status = "Y";
                }

                _context.Tblcustomers.Add(Tblcustomer);
                await _context.SaveChangesAsync();

                return RedirectToPage("./Index");
            }
            else
            {
                return Page();
            }

        }

        public int GetCodeCustomer() //Function Gen CodeCustomer
        {
            //string code;
            var qry = (from cus in _context.Tblcustomers select cus.Code).Count();
            var result = qry;

            return result;
        }
    }
}

FormWeb/Pages/Customer/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FormWeb.Models;

namespace FormWeb.Pages.Customer
{
    public class DeleteModel : PageModel
    {
        private readonly FormWeb.Models.ESHOPDBContext _context;

        public DeleteModel(FormWeb.Models.ESHOPDBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Tblcustomer Tblcustomer { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Tblcustomer = await _context.Tblcustomers.FirstOrDefaultAsync(m => m.Code == id);

            if (Tblcustomer == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Tblcustomer = await _context.Tblcustomers.FindAsync(id);

            if (Tblcustomer != null)
            {
                _context.Tblcustomers.Remove(Tblcustomer);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

FormWeb/Pages/Customer/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FormWeb.Models;
using FormWeb.ModelsMapping;

namespace FormWeb.Pages.Customer
{
    public class DetailsModel : PageModel
    {
        private readonly FormWeb.Models.ESHOPDBContext _context;

        public DetailsModel(FormWeb.Models.ESHOPDBContext context)
        {
            _context = context;
        }

        public Tblcustomer Tblcustomer { get; set; }

        public List<TBLCUSTOMERMAP> Tblcustomermap { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            List<TBLCUSTOMERMAP> tblcustomermap = await GetCustomer(id);

            Tblcustomermap = tblcustomermap;

            if (Tblcustomermap == null)
            {
                return NotFound();
            }
            return Page();

        }

        public async Task<List<TBLCUSTOMERMAP>> GetCustomer(string id)
        {
            return await Task.Run(() =>
            {
                var qry = (from cus in _context.Tblcustomers
                           join job in _context.Tbljobs on cus.Job equals job.Jobcode
                           where cus.Code == id && cus.Status == "Y"
                           select new TBLCUSTOMERMAP
                           {
                               Code = cus.Code,
                               Name = cus.Name,
                               Lastname = cus.Lastname,
                               JobName = job.Jobname,
                               Job = cus.Job,
                               Mobile = cus.Mobile,
                               CreateDate = cus.CreateDate,
                               Sex = cus.Sex,
                               Status = cus.Status
                           });
                return qry.ToList();
            });
        }
    }
}

FormWeb/Pages/Customer/Edit.cshtml.cs
using FormWeb.Models;
using FormWeb.ModelsMapping;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormWeb.Pages.Customer
{
    public class EditModel : PageModel
    {
        private readonly FormWeb.Models.ESHOPDBContext _context;

        private readonly UserManager<IdentityUser> userManager;

        private readonly SignInManager<IdentityUser> signInManager;

        public EditModel(FormWeb.Models.ESHOPDBContext context,
                             UserManager<IdentityUser> _userManager,
                             SignInManager<IdentityUser> _signInManager)
        {
            _context = context;
            userManager = _userManager;
            signInManager = _signInManager;
        }

        [BindProperty]
        public Tblcustomer Tblcustomer { get; set; }

        //public IndexModel indexModel { get; set; } หากต้องการใช้ Function จาก PageModel อื่นให้ประกาศแบบนี้

        [BindProperty]
        public List<TBLCUSTOMERMAP> Tblcustomermap { get; set; }

        [BindProperty]
        public List<Tbljob> Tbljobs { get; set; }

        public async Task<IActionResult> OnGet(string para)
        {
            Tbljobs = await _context.Tbljobs.ToListAsync();
            Tblcustomer tbl = new Tblcustomer();

            if (para == null)
            {
                return NotFound();
            }

            Tblcustomer = _context.Tblcustomers.Where(c => c.Code == para).FirstOrDefault();
            //Tblcustomermap = await GetEdit(para);

            if (Tblcustomer == null)
            {
                return NotFound();
            }

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostSuccess()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Tblcustomer != null)
            {
                Tblcustomer.Status = "Y";
            }

            _context.Attach(Tblcustomer).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TblcustomerExists(Tblcustomer.Code))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool TblcustomerExists(string id)
        {
            return _context.Tblcustomers.Any(e => e.Code == id);
        }

        public async Task<List<TBLCUSTOMERMAP>> GetEdit(string id)
        {
            return await Task.Run(() =>
            {
                var qry = (from cus in _context.Set<Tblcustomer>()
                           join job in _context.Set<Tbljob>()
                           on cus.Job equals job.Jobcode
                           where cus.Code == id && cus.Status == "Y"
                           select new TBLCUSTOMERMAP
                           {
                               Code = cus.Code,
                               Name = cus.Name,
                               Lastname = cus.Lastname,
                               JobName = job.Jobname,
                               Job = cus.Job,
                               Mobile = cus.Mobile,
                               CreateDate = cus.CreateDate,
                               Sex = cus.Sex,
                               Status = cus.Status
                           });

                return qry.ToListAsync();
            });
        }

        //public async Task<JsonResult> EditData([FromBody] TBLCUSTOMERMAP obj)
        //{
        //    string code = obj.Code;

        //    if (obj.Code != null)
        //    {
        //        Tblcustomermap = await GetEdit(code);
        //    }

        //    return new JsonResult(Tblcustomermap);
        //}

    }
}

FormWeb/Pages/Customer/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FormWeb.Models;
using Newtonsoft.Json;
using FormWeb.ModelsMapping;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace FormWeb.Pages.Customer
{
    public class IndexModel : PageModel
    {
        private readonly FormWeb.Models.ESHOPDBContext _context;

        private readonly UserManager<IdentityUser> userManager;

        private readonly SignInManager<IdentityUser> signInManager;

        public IndexModel(FormWeb.Models.ESHOPDBContext context,
                             UserManager<IdentityUser> _userManager,
                             SignInManager<IdentityUser> _signInManager)
        {
            _context = context;
            userManager = _userManager;
            signInManager = _signInManager;
        }

        public IList<Tblcustomer> Tblcustomer { get; set; }
        //public IList<TBLCUSTOMERMAP> TBLCUSTOMERMAP { get; set; }

        [BindProperty]
        public List<Tbljob> Tbljobs { get; set; }

        [BindProperty]
        public TBLCUSTOMERMAP Tblcusmap { get; set; }

        [BindProperty]
        public PaginationList<Tblcustomer> TBLCUSTOMERMAP { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        [BindProperty(SupportsGet = true)]
        public int pageIndex { get; set; } = 1;

        public async Task<IActionResult> OnGetAsync()
        {
            //string json;

            //Tblcustomer = await _context.Tblcustomers.ToListAsync();

            //TBLCUSTOMERMAP = (PaginationList<TBLCUSTOMERMAP>)Tblcustomer.Cast<TBLCUSTOMERMAP>();

            //json = JsonConvert.SerializeObject(Tblcustomer);

            try
            {
                Tbljobs = await _context.Tbljobs.ToListAsync();
                //List<TBLCUSTOMERMAP> tblcustomermap = JsonConvert.DeserializeObject<List<TBLCUSTOMERMAP>>(json);

                IQueryable<Tblcustomer> tblcustomermap;

                tblcustomermap = await GetCustomer();

                if (!string.IsNullOrEmpty(SearchString))
                {
                    tblcustomermap = tblcustomermap.Where(s => s.Code.Contains(SearchString.Trim()) ||
                                                          s.Name.Contains(SearchString.Trim()) ||
                                                          s.Mobile.Contains(SearchString.Trim()));
                }

                TBLCUSTOMERMAP = await PaginationList<Tblcustomer>.CreateAsync(tblcustomermap.AsNoTracking(), pageIndex, 3);
            }
            catch (Exception ex)
            {

            }

            return Page();
        }

        //public JsonResult OnPostEdit([FromBody] TBLCUSTOMERMAP Code)
        //{
        //    List<TBLCUSTOMERMAP> Ltblmap = new List<TBLCUSTOMERMAP>();
        //    string codes = Code.Code;
        //    if (Code.Code != null)
        //    {
        //        Ltblmap = GetEdit(codes);
        //        foreach (var item in Ltblmap)
        //        {
        //            Tblcusmap.Code = item.Code;
        //            Tblcusmap.Name = item.Name;
        //            Tblcusmap.Lastname = item.Lastname;
        //            Tblcusmap.Mobile = item.Mobile;
        //            Tblcusmap.Job = item.Job;
        //            Tblcusmap.JobName = item.JobName;
        //            Tblcusmap.Sex = item.Sex;
        //            Tblcusmap.CreateDate = item.CreateDate;
        //            Tblcusmap.Status = item.Status;
        //        }
        //    }

        //    return new JsonResult(Tblcusmap);
        //}

        public async Task<IQueryable<Tblcustomer>> GetCustomer()
        {
            return await Task.Run(() =>
            {
                var qry = (from cus in _context.Set<Tblcustomer>()
                           join job in _context.Set<Tbljob>()
                           on cus.Job equals job.Jobcode
                           where cus.Status == "Y"
                           orderby cus.Code descending
                           select new Tblcustomer
                           {
                               Code = cus.Code,
                               Name = cus.Name,
                               Lastname = cus.Lastname,
                               Mobile = cus.Mobile,
                               Job = job.Jobname,
                               //JobName = job.Jobname,
                               Sex = cus.Sex,
                               CreateDate = cus.CreateDate,
                               Status = cus.Status
                           });
                return qry;
            });
        }

        public List<TBLCUSTOMERMAP> GetEdit(string Code)
        {
            List<TBLCUSTOMERMAP> tblmap = new List<TBLCUSTOMERMAP>();
            var qry = (from cus in _context.Set<Tblcustomer>()
                       join job in _context.Set<Tbljob>()
                       on cus.Job equals job.Jobcode
                       where cus.Code == Code && cus.Status == "Y"
                       select new TBLCUSTOMERMAP
                       {
                           Code = cus.Code,
                           Name = cus.Name,
                           Lastname = cus.Lastname,
                           JobName = job.Jobname,
                           Job = cus.Job,
                           Mobile = cus.Mobile,
                           CreateDate = cus.CreateDate,
                           Sex = cus.Sex,
                           Status = cus.Status
                       });
            tblmap = qry.ToList();
            return tblmap;
        }
    }
}

FormWeb/Pages/Customer/Delete.cshtml
@page
@model FormWeb.Pages.Customer.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tblcustomer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tblcustomer.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tblcustomer.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tblcustomer.Lastname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tblcustomer.Lastname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tblcustomer.Mobile)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tblcustomer.Mobile)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tblcustomer.Job)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tblcustomer.Job)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tblcustomer.Sex)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tblcustomer.Sex)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tblcustomer.CreateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tblcustomer.CreateDate)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Tblcustomer.Code" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

FormWeb/Pages/Customer/Edit.cshtml
@page
@model FormWeb.Pages.Customer.EditModel

@{
    Layout = null;
    ViewData["Title"] = "Edit";
}

<form asp-page-handler="Success" class="row g-3" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="col-md-12">
        <label for="inputEmail4" class="form-label">Customer Code</label>
        <input asp-for="Tblcustomer.Code" type="text" readonly class="form-control" placeholder="First name">
        <span asp-validation-for="Tblcustomer.Code" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label for="inputEmail4" class="form-label">First Name</label>
        <input asp-for="Tblcustomer.Name" type="text" class="form-control" placeholder="First name">
        <span asp-validation-for="Tblcustomer.Name" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label for="inputEmail4" class="form-label">Last Name</label>
        <input asp-for="Tblcustomer.Lastname" type="text" class="form-control" placeholder="Last name">
        <span asp-validation-for="Tblcustomer.Lastname" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label for="inputEmail4" class="form-label">Mobile</label>
        <input asp-for="Tblcustomer.Mobile" type="text" class="form-control" placeholder="Mobile">
        <span asp-validation-for="Tblcustomer.Mobile" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label for="inputEmail4" class="form-label">Job</label>
        <select class="form-control" id="ddljob"
                asp-for="Tblcustomer.Job"
                asp-items="@(new SelectList(Model.Tbljobs,"Jobcode","Jobname"))">
            <option value="" selected disabled>-- กรุณาเลือก --</option>

        </select>
        <span asp-validation-for="Tblcustomer.Job" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label for="inputEmail4" class="form-label">Gender</label>
        <select class="form-control" id="ddljob"
                asp-for="Tblcustomer.Sex">
            <option value="" selected disabled>-- กรุณาเลือก --</option>
            <option value="Male">Male</option>
            <option value="Female">Female</option>
        </select>
        <span asp-validation-for="Tblcustomer.Sex" class="text-danger"></span>
    </div>
    @*<div class="col-md-6">
        <label for="inputEmail4" class="form-label">Start Date</label>
        <input asp-for="Tblcustomer.CreateDate" class="form-control" type="date" placeholder="Start Date">
        <span asp-validation-for="Tblcustomer.CreateDate" class="text-danger"></span>
    </div>*@
    <div btm class="col-12">
        <label for="inputEmail4" class="form-label"></label>
        <input type="submit" value="Submit" class="btn-outline-success btn-sm btn-block" />
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FormWeb/Pages/Customer/Index.cshtml
@page
@model FormWeb.Pages.Customer.IndexModel

@{
    ViewData["Title"] = "Index";
}

@Html.AntiForgeryToken()
@if (TempData["success"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["success"]
    </div>
}
<div class="card">
    <div class="card-header">
        รายการลูกค้า
    </div>
    <div><hr></div>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <p>
                    <button type="button" onclick="showInPopup('/Customer/Create','Create New')" class="btn btn-success">เพิ่มประวัติลูกค้า</button>
                </p>
            </div>
            <div class="col-sm-6">
                <form class="form-inline">
                    <input asp-for="SearchString" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"> &ensp;
                    <input class="btn btn-success my-2 my-sm-0" type="submit" value="Search" /> &nbsp; | &nbsp;
                    <a asp-page="Index" class="btn btn-warning my-2 my-sm-0" type="submit" formmethod="get">Clear</a>
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover mx-auto w-auto" style="text-align-last: center;">
                <thead>
                    <tr>
                        <th style="color: #000000;">
                            @Html.DisplayNameFor(model => model.TBLCUSTOMERMAP[0].Code)
                        </th>
                        <th style="color: #000000;">
                            @Html.DisplayNameFor(model => model.TBLCUSTOMERMAP[0].Name) - @Html.DisplayNameFor(model => model.TBLCUSTOMERMAP[0].Lastname)
                        </th>
                        <th style="color: #000000;">
                            @Html.DisplayNameFor(model => model.TBLCUSTOMERMAP[0].Mobile)
                        </th>
                        <th style="color: #000000;">
                            @Html.DisplayNameFor(model => model.TBLCUSTOMERMAP[0].Job)
                        </th>
                        <th style="color: #000000;">
                            @Html.DisplayNameFor(model => model.TBLCUSTOMERMAP[0].Sex)
                        </th>
                        <th style="color: #000000;">
                            @Html.DisplayNameFor(model => model.TBLCUSTOMERMAP[0].CreateDate)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.TBLCUSTOMERMAP)
                    {
                        <tr>
                            <td>
                                <a asp-page="./Details" asp-route-id="@item.Code">
                                    @Html.DisplayFor(modelItem => item.Code)
                                </a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)  @Html.DisplayFor(modelItem => item.Lastname)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mobile)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Job)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sex)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreateDate)
                            </td>
                            <td>
                                <button type="button" class="btn btn-md btn-success" onclick="EditData('/Customer/Edit','@item.Code','Edit Customer');">Edit</button> &ensp;
                                <a class="btn btn-md btn-danger" asp-page="./Delete" asp-route-id="@item.Code">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-sm-4">
            @{
                var prevDisabled = !Model.TBLCUSTOMERMAP.PreviousPage ? "disabled" : "";
                var nextDisabled = !Model.TBLCUSTOMERMAP.NextPage ? "disabled" : "";
            }

            <a asp-page="/Customer/Index"
               asp-route-pageIndex="@(Model.TBLCUSTOMERMAP.PageIndex - 1)"
               class="btn btn-primary @prevDisabled">
                Previous
            </a>
            <a name="plus" asp-page="/Customer/Index"
               asp-route-pageIndex="@(Model.TBLCUSTOMERMAP.PageIndex + 1)"
               class="btn btn-primary @nextDisabled">
                Next
            </a>
        </div>
    </div>
    <div class="card-footer">
    </div>
</div>




<!--Modal-->
@*<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form asp-page="./Edit" asp-page-handler="Success" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Tblcusmap.Code" class="control-label"></label>
                            <input id="Code" asp-for="Tblcusmap.Code" class="form-control" readonly="readonly" />
                            <span asp-validation-for="Tblcusmap.Code" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tblcusmap.Name" class="control-label"></label>
                            <input id="Name" asp-for="Tblcusmap.Name" class="form-control" />
                            <span asp-validation-for="Tblcusmap.Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tblcusmap.Lastname" class="control-label"></label>
                            <input id="Lastname" asp-for="Tblcusmap.Lastname" class="form-control" />
                            <span asp-validation-for="Tblcusmap.Lastname" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tblcusmap.Mobile" class="control-label"></label>
                            <input id="Mobile" asp-for="Tblcusmap.Mobile" class="form-control" />
                            <span asp-validation-for="Tblcusmap.Mobile" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tblcusmap.Job" class="control-label"></label>
                            <select class="form-control" id="Job"
                                    asp-for="Tblcusmap.Job"
                                    asp-items="@(new SelectList(Model.Tbljobs,"Jobcode","Jobname"))">
                                <option value="" selected disabled>-- กรุณาเลือก --</option>

                            </select>

                            <input asp-for="Tblcustomer.Job" class="form-control" />
                            <span asp-validation-for="Tblcusmap.Job" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tblcusmap.Sex" class="control-label"></label>
                            <input id="Sex" asp-for="Tblcusmap.Sex" class="form-control" />
                            <span asp-validation-for="Tblcusmap.Sex" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>


        function EditData(v) {




            $.ajax(
                {
                    url: "/Customer/Index?handler=Edit",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("XSRF-TOKEN",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },

                    dataType: "json",

                    data: JSON.stringify(
                        {
                            "Code": v

                        }),


                    contentType: "application/json; charset=utf-8",

                    type: "POST",

                    success: function (response) {



                        $("#Code").val(response["code"]);

                        $("#Name").val(response["name"]);
                        $("#Lastname").val(response["lastname"]);
                        $("#Mobile").val(response["mobile"]);
                        $("#Job").val(response["job"]);
                        $("#Sex").val(response["sex"]);

                        $('#exampleModal').modal('show');
                    },

                    error: function (data) {


                    }


                })
        }



    </script>*@