FormWeb/Pages/EmpInfo/CreateEmp.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using FormWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace FormWeb.Pages.EmpInfo
{
    public class CreateEmpModel : PageModel
    {
        private readonly FormWeb.Models.ESHOPDBContext _context;

        public CreateEmpModel(FormWeb.Models.ESHOPDBContext context)
        {
            _context = context;
        }

        public async Task OnGetAsync()
        {
            Tbldepartment = await _context.Tbldepartments.ToListAsync();
            Tblposition = await _context.Tblpositions.ToListAsync();
        }

        public ManageEmpModel manageEmp { get; set; }

        [BindProperty]
        public Tblemployee Tblemployee { get; set; }
        [BindProperty]
        public List<Tbldepartment> Tbldepartment { get; set; }
        [BindProperty]
        public List<Tblposition> Tblposition { get; set; }

        public string Message { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                if(Tblemployee.Id <= 0)
                {
                    InsertEmp(Tblemployee);

                    Tblemployee.Status = "Y";

                    _context.Tblemployees.Add(Tblemployee);

                    await _context.SaveChangesAsync();

                    return RedirectToPage("/EmpInfo/ManageEmp");
                }
                //HttpContext.Session.SetString("SessionEmp", JsonConvert.SerializeObject(Tblemployee)); /*Session For object*/
                TempData["Message"] = Message = "กรุณาลองใหม่อีกครั้ง";

                return RedirectToPage("/EmpInfo/ManageEmp");
            }

            return Page();

        }

        public void InsertEmp(Tblemployee empCode)
        {
            string dt = DateTime.Now.Ticks.ToString();

            string Code = "EP" + dt.Substring(dt.Length - 5, 5);

            empCode.EmpCode = Code;
        }
    }

}

FormWeb/Pages/EmpInfo/EditEmp.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FormWeb.Models;
using FormWeb.ModelsMapping;
using Newtonsoft.Json;

namespace FormWeb.Pages.EmpInfo
{
    public class EditEmpModel : PageModel
    {
        private readonly FormWeb.Models.ESHOPDBContext _context;

        public EditEmpModel(FormWeb.Models.ESHOPDBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Tblemployee Tblemployees { get; set; }

        [BindProperty]
        public TblEmpolyeemap TblEmpolyeemaps { get; set; }

        public IList<Tblposition> Tblposition { get; set; }

        public IList<Tbldepartment> Tbldepartment { get; set; }

        public async Task<IActionResult> OnGetAsync(int para)
        {
            Tbldepartment = await _context.Tbldepartments.ToListAsync();
            Tblposition = await _context.Tblpositions.ToListAsync();

            var employees = _context.Tblemployees.Where(e => e.Id == para).AsQueryable();

            Tblemployees = await employees.FirstOrDefaultAsync();

            if (Tblemployees == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            Tblemployee empobj = new Tblemployee();

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (TblEmpolyeemaps != null)
            {
                TblEmpolyeemaps.Status = "Y";

                string json = JsonConvert.SerializeObject(TblEmpolyeemaps);

                empobj = JsonConvert.DeserializeObject<Tblemployee>(json);
            }
            Tblemployees = empobj;

            _context.Attach(Tblemployees).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TblemployeeExists(Tblemployees.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./ManageEmp");
        }

        private bool TblemployeeExists(int id)
        {
            return _context.Tblemployees.Any(e => e.Id == id);
        }

        //public async Task<List<TblEmpolyeemap>> GetEmployee(int para)
        //{
        //    return await Task.Run(() =>
        //    {
        //        var qry = from emp in _context.Set<Tblemployee>()
        //                  join dep in _context.Set<Tbldepartment>()
        //                  on emp.DepartmentCode equals dep.DepartmentCode
        //                  join pst in _context.Set<Tblposition>()
        //                  on emp.Position equals pst.PositionCode
        //                  where emp.Id == para && emp.Status == "Y"
        //                  select new TblEmpolyeemap
        //                  {
        //                      Id = emp.Id,
        //                      EmpCode = emp.EmpCode,
        //                      EmpName = emp.EmpName,
        //                      EmpLastName = emp.EmpLastName,
        //                      Email = emp.Email,
        //                      Mobile = emp.Mobile,
        //                      DepartmentCode = emp.DepartmentCode,
        //                      DepartmentName = dep.DepartmentName,
        //                      Position = emp.Position,
        //                      PositionName = pst.PositionName,
        //                      Role = emp.Role,
        //                      Status = emp.Status,
        //                      CreateDate = emp.CreateDate
        //                  };

        //        return qry.ToListAsync();
        //    });
        //}
    }
}

FormWeb/Pages/EmpInfo/EmpDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using FormWeb.Models;
using FormWeb.ModelsMapping;
using Microsoft.AspNetCore.Identity;

namespace FormWeb.Pages.EmpInfo
{
    public class EmpDetailsModel : PageModel
    {
        private readonly FormWeb.Models.ESHOPDBContext _context;

        private readonly UserManager<IdentityUser> userManager; //Consturctor asp.net Identity For Create User

        private readonly SignInManager<IdentityUser> signInManager; //Consturctor asp.net Identity For Sign in

        public EmpDetailsModel(FormWeb.Models.ESHOPDBContext context,
                             UserManager<IdentityUser> _userManager,
                             SignInManager<IdentityUser> _signInManager)
        {
            _context = context;
            userManager = _userManager;
            signInManager = _signInManager;
        }

        #region Binding Get

        public IList<TblRole> TblRoleselect { get; set; }

        public Tblemployee Tblemployee { get; set; }

        public List<TblEmpRole> getEmpRole { get; set; }

        #endregion

        #region Binding Post

        [BindProperty]
        public TblEmpolyeemap TblEmpolyeemaps { get; set; }

        [BindProperty]
        public TblEmpRole EmpRole { get; set; }

        [BindProperty]
        public Tbluser UserRegis { get; set; }

        #endregion

        public async Task<IActionResult> OnGetAsync(int? para) // Get Emp, UserLogin, Roles
        {
            if (para == 0)
            {
                return NotFound(); //ต้องทำ Message บอกเพิ่มแล้ว Redirect กลับไปหน้า ManageEmp
            }
            else
            {
                var tblmap = await GetEmployee((int)para);


                Tblemployee = await tblmap.FirstOrDefaultAsync();
            }

            if (Tblemployee == null)
            {

                return NotFound(); //ต้องทำ Message บอกเพิ่มแล้ว Redirect กลับไปหน้า ManageEmp
            }

            bool CheckEmpUser = TblUserExists(Tblemployee.EmpCode);

            if (CheckEmpUser == true)
            {
                var qyrUser = _context.Tblusers.AsQueryable().Where(u => u.EmpCode == Tblemployee.EmpCode);

                if (qyrUser != null)
                {
                    UserRegis = await qyrUser.FirstOrDefaultAsync();
                }

                var qryEmprole = _context.TblEmpRoles.AsQueryable().Where(er => er.EmpCode == Tblemployee.EmpCode);

                if (qryEmprole != null)
                {
                    getEmpRole = await qryEmprole.ToListAsync();
                }
            }

            TblRoleselect = await _context.TblRoles.ToListAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostRegisterAndEdit(string Codepara, int Idpara) //Post ส่วนของ Register
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (UserRegis.Password != UserRegis.ConfirmPassword)
            {
                return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
            }

            var checkEmp = TblEmpCheck(Codepara);
            var checkUserLogin = TblUserExists(Codepara);

            if (checkEmp == true)
            {
                if(checkUserLogin == false) //Insert
                {
                    IdentityUser user = new IdentityUser { UserName = UserRegis.Username, PasswordHash = UserRegis.Password };

                    var result = await userManager.CreateAsync(user, UserRegis.Password); // Insert User

                    if (result.Succeeded) // ต้องเข้าเงื่อนไขของการสร้างรหัสถึงจะ สามารถบันทึกลง base ได้
                    {
                        if (UserRegis.EmpCode == null )
                        {
                            UserRegis.EmpCode = Codepara;
                        }

                        _context.Tblusers.Add(UserRegis);
                        await _context.SaveChangesAsync();

                        return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
                    } 
                }

                //else //Update
                //{                   

                //    IdentityUser user = new IdentityUser { UserName = UserRegis.Username, PasswordHash = UserRegis.Password };

                //    var result = await userManager.get // Update User

                //    if (result.Succeeded) // ต้องเข้าเงื่อนไขของการสร้างรหัสถึงจะ สามารถบันทึกลง base ได้
                //    {

                //        _context.Attach(UserRegis).State = EntityState.Modified;
                //        await _context.SaveChangesAsync();

                //        return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
                //    }

                //}
                
            }

            return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
        }

        public async Task<IActionResult> OnPostAddRole(string para, int Idpara) // Add Roles
        {
            TblEmpRole empRole = new TblEmpRole();

            if (para == null && para == "")
            {
                return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
            }

            bool checkEmp = TblEmpCheck(para); 
            if (checkEmp == true)
            {
                if (EmpRole.RoleId != null)
                {
                    TblRole role = new TblRole();
                    int roleId = int.Parse(EmpRole.RoleId);

                    var getRole = _context.TblRoles.AsQueryable();

                    role = await _context.TblRoles.Where(r => r.Id == roleId).FirstOrDefaultAsync();

                    if (role != null)
                    {
                        EmpRole.EmpCode = para;
                        EmpRole.RoleId = role.Id.ToString();
                        EmpRole.RoleName = role.Role;

                        _context.TblEmpRoles.Add(EmpRole);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
                    }
                }
                else
                {
                    return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
                }
            }

            return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });

        }

        public async Task<IActionResult> OnPostDeleteRole(int id, int Idpara)
        {
            if(id == 0)
            {
                return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
            }

            TblEmpRole emprole = new TblEmpRole();
            emprole = TbldeleteRole(id);

            if(emprole != null)
            {
                _context.TblEmpRoles.Remove(emprole);

                await _context.SaveChangesAsync();
            }
            else
            {
                return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });
            }

            return RedirectToPage("/EmpInfo/EmpDetails", new { para = Idpara });

        } //DeleteRole

        private TblEmpRole TbldeleteRole(int id)
        {
            var qry = _context.TblEmpRoles.AsQueryable().Where(role => role.Id == id);

            return qry.FirstOrDefault();
        }

        private bool TblUserExists(string para) //Check User data have Empcode for UserLogin
        {
            var qry = _context.Tblusers.AsQueryable().Any(user => user.EmpCode == para);
            return qry;
        }

        private bool TblEmpCheck(string Codepara) //Check Paramrter EmpCode if Fine will Use For Insert to TblUser
        {
            var qry = _context.Tblemployees.AsQueryable().Any(e => e.EmpCode == Codepara);
            return qry;
        }

        public async Task<IQueryable<Tblemployee>> GetEmployee(int para)  //Query map ข้อมูล
        {
            return await Task.Run(() =>
            {
                var qry = from emp in _context.Set<Tblemployee>()
                          join dep in _context.Set<Tbldepartment>()
                          on emp.DepartmentCode equals dep.DepartmentCode
                          into Dep
                          from dep in Dep.DefaultIfEmpty()
                          join pst in _context.Set<Tblposition>()
                          on emp.Position equals pst.PositionCode
                          into Pot
                          from pst in Pot.DefaultIfEmpty()
                          where emp.Id == para && emp.Status == "Y"
                          select new Tblemployee
                          {
                              Id = emp.Id,
                              EmpCode = emp.EmpCode,
                              EmpName = emp.EmpName,
                              EmpLastName = emp.EmpLastName,
                              Email = emp.Email,
                              Mobile = emp.Mobile,
                              DepartmentCode = emp.DepartmentCode,
                              Department = dep == null ? "" : dep.DepartmentName,
                              Position = emp.Position,
                              PositioN = pst == null ? "" : pst.PositionName,
                              Status = emp.Status,
                              CreateDate = emp.CreateDate
                          };

                return qry;
            });
        }
    }
}

FormWeb/Pages/EmpInfo/CreateEmp.cshtml
@page
@model FormWeb.Pages.EmpInfo.CreateEmpModel

@{
    ViewData["Title"] = "Create";
    Layout = null;
}
<form class="row g-3" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="col-md-6">
        <label for="inputEmail4" class="form-label">ชื่อ</label>
        <input asp-for="Tblemployee.EmpName" type="text" class="form-control" placeholder="First name">
        <span asp-validation-for="Tblemployee.EmpName" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label for="inputEmail4" class="form-label">นามสกุล</label>
        <input asp-for="Tblemployee.EmpLastName" type="text" class="form-control" placeholder="Last name">
        <span asp-validation-for="Tblemployee.EmpLastName" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label for="inputEmail4" class="form-label">เบอร์โทรศัพท์</label>
        <input asp-for="Tblemployee.Mobile" type="text" class="form-control" placeholder="Mobile">
        <span asp-validation-for="Tblemployee.Mobile" class="text-danger"></span>
    </div>
    <div class="col-md-6">
        <label for="inputEmail4" class="form-label">E-mail</label>
        <input asp-for="Tblemployee.Email" type="text" class="form-control" placeholder="Mobile">
        <span asp-validation-for="Tblemployee.Email" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label for="inputEmail4" class="form-label">แผนก
        </label>
        <select class="form-control" id="ddljob"
                asp-for="Tblemployee.DepartmentCode"
                asp-items="@(new SelectList(Model.Tbldepartment,"DepartmentCode","DepartmentName"))">
            <option value="" selected disabled>-- กรุณาเลือก --</option>

        </select>
        <span asp-validation-for="Tblemployee.DepartmentCode" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label for="inputEmail4" class="form-label">ตำแหน่ง</label>
        <select class="form-control" id="ddlPosition"
                asp-for="Tblemployee.Position"
                asp-items="@(new SelectList(Model.Tblposition,"PositionCode","PositionName"))">
            <option value="" selected disabled>-- กรุณาเลือก --</option>
        </select>
        <span asp-validation-for="Tblemployee.Position" class="text-danger"></span>
    </div>
    <div class="col-md-4">
        <label for="inputEmail4" class="form-label">วันที่เริ่มทำงาน</label>
        <input asp-for="Tblemployee.CreateDate" class="form-control" type="date" placeholder="วัน/เดือน/ปี">
        <span asp-validation-for="Tblemployee.CreateDate" class="text-danger"></span>
    </div>
    <div class="col-12">
        <label for="inputEmail4" class="form-label"></label>
        <input type="submit" asp-page="/EmpInfo/CreateEmp" value="Submit" class="btn-outline-primary btn-sm btn-block" />
    </div>
</form>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

FormWeb/Pages/EmpInfo/EmpDetails.cshtml
@page
@model FormWeb.Pages.EmpInfo.EmpDetailsModel

@{
    ViewData["Title"] = "EmpDetails";
}

<div class="card">
    <div class="card-header">
        รายละเอียดพนักงาน
    </div>
    <div><hr></div>
    <div class="card-body">
        <div class="col-sm-12 d-flex justify-content-center">
            <dl class="row">
                <dd hidden>
                    @Html.DisplayNameFor(model => model.Tblemployee.Id)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Tblemployee.EmpCode)
                </dt>
                <dd class="col-sm-4">
                    @Html.DisplayFor(model => model.Tblemployee.EmpCode)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Tblemployee.EmpName) - @Html.DisplayNameFor(model => model.Tblemployee.EmpLastName)
                </dt>
                <dd class="col-sm-4">
                    @Html.DisplayFor(model => model.Tblemployee.EmpName) @Html.DisplayFor(model => model.Tblemployee.EmpLastName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Tblemployee.Mobile)
                </dt>
                <dd class="col-sm-4">
                    @Html.DisplayFor(model => model.Tblemployee.Mobile)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Tblemployee.Email)
                </dt>
                <dd class="col-sm-4">
                    @Html.DisplayFor(model => model.Tblemployee.Email)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Tblemployee.Department)
                </dt>
                <dd class="col-sm-4">
                    @Html.DisplayFor(model => model.Tblemployee.Department)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Tblemployee.PositioN)
                </dt>
                <dd class="col-sm-4">
                    @Html.DisplayFor(model => model.Tblemployee.PositioN)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Tblemployee.CreateDate)
                </dt>
                <dd class="col-sm-4">
                    @Html.DisplayFor(model => model.Tblemployee.CreateDate)
                </dd>
            </dl>

        </div>
        <div class="col-sm-4">
            <a class="btn btn-success" role="button" asp-page="./EditEmp" asp-route-para="@Model.Tblemployee.Id">Edit</a> |
            <a class="btn btn-danger" role="button" asp-page="./Index">Back to List</a>
        </div>
    </div>
</div>

@if (Model.UserRegis != null)
{
    <div class="card">
        <div class="card-header">
            User & Password
        </div>
        <div><hr></div>
        <div class="card-body">
            <div class="col-sm-12" style="align-items:center">
                <form asp-page="/EmpInfo/EmpDetails" asp-page-handler="RegisterAndEdit" asp-route-Codepara="@Model.Tblemployee.EmpCode" asp-route-Idpara="@Model.Tblemployee.Id" method="POST" class="row g-3">
                    <div class="col-md-4">
                        <label for="inputEmail4" class="form-label">User</label>
                        <input asp-for="UserRegis.Username" type="text" required="" class="form-control" oninvalid="this.setCustomValidity('กรุณากรอกชื่อ')"
                               oninput="setCustomValidity('')" placeholder="Username">
                        <span asp-validation-for="UserRegis.Username" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputEmail4" class="form-label">Password</label>
                        <input asp-for="UserRegis.Password" required="" class="form-control" oninvalid="this.setCustomValidity('กรุณากรอกนามสกุล')"
                               oninput="setCustomValidity('')" placeholder="Password">
                        <span asp-validation-for="UserRegis.Password" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputEmail4" class="form-label">Confirm-Password</label>
                        <input asp-for="UserRegis.ConfirmPassword" required="" class="form-control" oninvalid="this.setCustomValidity('กรุณากรอกเบอร์โทรศัพท์')"
                               oninput="setCustomValidity('')" placeholder="ConfirmPassword">
                    </div>
                    <div class="col-sm-12">
                        <div class="text-center">
                            <input class="btn btn-warning my-2 my-sm-0" type="submit" value="Change Password" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
}
else
{
    <div class="card">
        <div class="card-header">
            User & Password
        </div>
        <div><hr></div>
        <div class="card-body">
            <div class="col-sm-12" style="align-items:center">
                <form asp-page="/EmpInfo/EmpDetails" asp-page-handler="RegisterAndEdit" asp-route-Codepara="@Model.Tblemployee.EmpCode" asp-route-Idpara="@Model.Tblemployee.Id" method="POST" class="row g-3">
                    <div class="col-md-4">
                        <label for="inputEmail4" class="form-label">User</label>
                        <input asp-for="UserRegis.Username" type="text" required="" class="form-control" oninvalid="this.setCustomValidity('กรุณากรอกชื่อ')"
                               oninput="setCustomValidity('')" placeholder="Username">
                        <span asp-validation-for="UserRegis.Username" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputEmail4" class="form-label">Password</label>
                        <input asp-for="UserRegis.Password" required="" class="form-control" oninvalid="this.setCustomValidity('กรุณากรอกนามสกุล')"
                               oninput="setCustomValidity('')" placeholder="Password">
                        <span asp-validation-for="UserRegis.Password" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label for="inputEmail4" class="form-label">Confirm-Password</label>
                        <input asp-for="UserRegis.ConfirmPassword" required="" class="form-control" oninvalid="this.setCustomValidity('กรุณากรอกเบอร์โทรศัพท์')"
                               oninput="setCustomValidity('')" placeholder="ConfirmPassword">
                    </div>
                    <div class="col-sm-12">
                        <div class="text-center">
                            <input class="btn btn-success my-2 my-sm-0" type="submit" value="Submit" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
}

@Html.AntiForgeryToken()
<div class="card">
    <div class="card-header">
        จัดการสิทธิ์พนักงาน
    </div>
    <div><hr></div>
    <div class="card-body">
        <div class="col-sm-12">
            <div class="col-sm-6">
                <form asp-page="/EmpInfo/EmpDetails" asp-page-handler="AddRole" asp-route-para="@Model.Tblemployee.EmpCode" asp-route-Idpara="@Model.Tblemployee.Id" method="POST" class="row g-3">
                    <select class="form-control" asp-for="EmpRole.RoleId" id="Select1"
                            asp-items="@(new SelectList(Model.TblRoleselect,"Id","Role"))">
                        <option></option>

                        <option value="" selected disabled>-- กรุณาเลือก --</option>

                    </select>
                    <div class="col-sm-2">
                        <input class="btn btn-success my-2 my-sm-0" type="submit" value="Sumbit" />
                    </div>
                </form>
            </div>
            @if (Model.getEmpRole != null)
            {
                <div class="table-responsive">
                    <table class="table table-hover mx-auto w-auto" style="text-align-last: center;">
                        <thead>
                            <tr>
                                <th hidden style="color: #000000;">
                                    @Html.DisplayNameFor(model => model.getEmpRole[0].Id)
                                </th>
                                <th style="color: #000000;">
                                    @Html.DisplayNameFor(model => model.getEmpRole[0].RoleName)
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.getEmpRole)
                            {
                                <tr>
                                    <td hidden>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.RoleName)
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}